homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url

# Discover some devices automatically
discovery:

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      # - type: ipv4_address
      #   arg: wlan0
      - type: last_boot
      # - type: since_last_boot
  - platform: uptime
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "C"
    value_template: '{{ value | multiply(0.001) | round(0) }}'
  - platform: template
    sensors:
      ram_use_percent:
        friendly_name: "Memory Used %"
        unit_of_measurement: '%'
        value_template: "{{states.sensor.memory_use_percent.state | round}}"
      cpu_use:
        friendly_name: "CPU Used %"
        unit_of_measurement: '%'
        value_template: "{{states.sensor.processor_use.state | multiply(0.5) | round | multiply(2)}}"
      uptime_v2:
        friendly_name: Uptime (days)
        unit_of_measurement: days
        value_template: '{% set uptime_num = states.sensor.uptime.state|float %}
                         {% if uptime_num <=1 -%}
                         {{uptime_num  | round(1)}}
                         {%- else -%}
                         {{uptime_num  | round}}
                         {%- endif %}'

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

tplink:
  discovery: false
  switch:
    - host: 192.168.29.134
    - host: 192.168.29.170
    - host: 192.168.29.200
    
eufy:
  # username: !secret eufy_username
  # password: !secret eufy_password
  devices:
    - address: 192.168.29.194
      access_token: !secret eufy_bulb_access_token
      type: T1012
      name: Night Lamp

recorder:  
  db_url: !secret db_url
  purge_keep_days: 2
  exclude:
    entities:
      - sun.sun
      - sensor.since_last_boot
      - sensor.ipv4_address_eth0
      - sensor.ipv4_address_wlan0
      - sensor.disk_use_percent_home
      - sensor.cpu_temperature
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.uptime
    domains:
      - media_player
